[build]
  # Set the directory where your site's files are located
  publish = "./"
  functions = "./functions"

  # Uncomment if you have build commands (e.g., npm run build)
  # command = "npm run build"


[[redirects]]
  # Redirects to handle SPA routing or custom needs (optional)
  from = "/*"
  to = "/index.html"
  status = 200